// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footnotes: dynamic(() => import("./Footnotes")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  opening: dynamic(() => import("./Opening")),
  quote: dynamic(() => import("./Quote")),
  table: dynamic(() => import("./Table")),
  text: dynamic(() => import("./Text")),
};
